import {
    GraphQLInputObjectType,
    GraphQLString,
    GraphQLList,
    GraphQLID,
    GraphQLObjectType,
    GraphQLFloat,
    GraphQLInt,
    GraphQLBoolean,
    GraphQLNonNull
} from 'graphql'
import {RecordType} from './records';
import Record from '../../models/records';

export const DeviceType = new GraphQLObjectType({
    name:"ListDevices",
    description:"Dispositivos de la BD",
    fields: () => ({
        _id:{
            type:GraphQLNonNull(GraphQLID)
        },
        sigfox:{
            type:GraphQLString
        },
        concesion:{
            type:GraphQLString
        },
        name:{
            type:GraphQLString
        },

        marcaVehicle:{
            type:GraphQLString
        },
        modeloVehicle:{
            type:GraphQLString
        },
        anioVehicle:{
            type:GraphQLString
        },
        placaVehicle:{
            type:GraphQLString
        },
        image_url_fvehicle:{
            type:GraphQLString
        },
        image_url_lvehicle:{
            type:GraphQLString
        },
        image_url_rvehicle:{
            type:GraphQLString
        },
        image_url_bvehicle:{
            type:GraphQLString
        },
        image_url_conductor:{
            type:GraphQLString
        },
        conductorName:{
            type:GraphQLString
        },
        conductorLastname:{
            type:GraphQLString
        },
        conductorAddress:{
            type:GraphQLString
        },
        conductorDistrict:{
            type:GraphQLString
        },
        conductorNumExt:{
            type:GraphQLString
        },
        conductorNumInt:{
            type:GraphQLString
        },
        conductorTel:{
            type:GraphQLString
        },
        conductorCC:{
            type:GraphQLString
        },
        conductorCity:{
            type:GraphQLString
        },
        conductorCountry:{
            type:GraphQLString
        },
        velocidadMaxima:{
            type:GraphQLString
        },
        initTravel:{
            type:GraphQLList(GraphQLString)
        },
        lastLocation:{
            type:GraphQLString
        },
        contTravel:{
            type:GraphQLInt
        },
        contTime:{
            type:GraphQLInt
        },
        contKm:{
            type:GraphQLInt
        },
        contEfectivo:{
            type:GraphQLFloat
        },
        user:{
            type:GraphQLString
        },
        records:{
            type:GraphQLList(RecordType),
            resolve(device){
                const {records} = device
                return Record.find({_id:{$in:records}}).sort('concesion').then((rec) => {
                    return rec
                })
            }
        },
        create_at:{
            type:GraphQLString
        },
        update_at:{
            type:GraphQLString
        }
        
    })
});

export const DeviceInputType = new GraphQLInputObjectType({
    
    name:"addDevices",
    description:"Agrega o modifica dispositivos en la bd",
    fields: () => ({
        sigfox:{
            type:GraphQLString
        },
        concesion:{
            type:GraphQLString
        },
        name:{
            type:GraphQLString
        },
        user:{
            type:GraphQLString
        },
        records:{
            type:GraphQLString
        },
        marcaVehicle:{
            type:GraphQLString
        },
        modeloVehicle:{
            type:GraphQLString
        },
        anioVehicle:{
            type:GraphQLString
        },
        placaVehicle:{
            type:GraphQLString
        },
        image_url_fvehicle:{
            type:GraphQLString
        },
        image_url_lvehicle:{
            type:GraphQLString
        },
        image_url_rvehicle:{
            type:GraphQLString
        },
        image_url_bvehicle:{
            type:GraphQLString
        },
        image_url_conductor:{
            type:GraphQLString
        },
        conductorName:{
            type:GraphQLString
        },
        conductorLastname:{
            type:GraphQLString
        },
        conductorAddress:{
            type:GraphQLString
        },
        conductorDistrict:{
            type:GraphQLString
        },
        conductorNumExt:{
            type:GraphQLString
        },
        conductorNumInt:{
            type:GraphQLString
        },
        conductorTel:{
            type:GraphQLString
        },
        conductorCC:{
            type:GraphQLString
        },
        conductorCity:{
            type:GraphQLString
        },
        conductorCountry:{
            type:GraphQLString
        },
        initTravel:{
            type:GraphQLString
        }
    })
})
